### ISSUE TITLE
Chemin OSC supplémentaire

### ISSUE THREAD

**Issue by groolot** [Raidez/Android-ProMask#2]
J'ai rajouté une méthode OSC https://github.com/PMO-Ecluse/mallarmeGenerateur3D/blob/masquage/src/Masque.cpp#L113

elle permet de gérer la couleur du masque :
`/mallarme/masque/color fff 0.5 0.5 0.5`
donne un masque gris, tandis que :
`/mallarme/masque/color fff 0 1 0`
donne un masque vert.

on pourrait envisager que ce soit intégrable dans ton code avec une roue colorée où il suffit de choisir la couleur à l'œil comme ça :  https://github.com/yukuku/ambilwarna

**Comment by Raidez** [comment]
Avant d'ajouter cette fonctionnalité, je dois livrer une version fonctionnelle et configurable, je vous renverrais un message une fois l'application terminée (respectant le 1er cahier des charges)
